seed: 42

data:
  path: src/data/creditcard.csv
  target: Class
  test_size: 0.25
  stratify: true
  scale: true
  balance: none

model:
  name: isolation_forest
  params:
    n_estimators: 100
    contamination: 0.0017
    random_state: 42
    n_jobs: -1

evaluation:
  cv:
    enabled: true
    folds: 5
  metrics: [average_precision, roc_auc, f1, precision, recall]
  threshold:
    optimize_for: f1
    search_space: [0.01, 0.99]
    steps: 200

outputs:
  dir: experiments/isolation_forest
  save_plots: true
  save_model: true
  save_metrics: true
