seed: 42

data:
  path: src/data/creditcard.csv
  target: Class
  test_size: 0.25
  stratify: true
  scale: true
  balance: smote

model:
  name: random_forest
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1

evaluation:
  cv:
    enabled: true
    folds: 5
  metrics: [average_precision, roc_auc, f1, precision, recall]
  threshold:
    optimize_for: f1
    search_space: [0.01, 0.99]
    steps: 200

outputs:
  dir: experiments/random_forest_smote
  save_plots: true
  save_model: true
  save_metrics: true
